### ISSUE TITLE
Error During Training

### ISSUE THREAD

**Issue by takeofuture** [sonyc-project/dcase2020task5-uststc-baseline#7]
Hi Thank you for sharing this task5 base line
However, I got error during the training.
I am not sure this comes from the some corrupted data in embedding or code
```
dcase2020task5-uststc-baseline/src$ python classify.py $SONYC_UST_PATH/data/annotations.csv $SONYC_UST_PATH/data/dcase-ust-taxonomy.yaml $SONYC_UST_PATH/embeddings $SONYC_UST_PATH/output baseline_fine --label_mode fine
```

```
Epoch 25/100
 - 1s - loss: 122.2184 - val_loss: 178.2631
Epoch 26/100
 - 1s - loss: 119.3532 - val_loss: 183.5670
Epoch 27/100
 - 1s - loss: 116.4432 - val_loss: 185.7071
Epoch 28/100
 - 1s - loss: 113.5450 - val_loss: 186.4551
* Saving model predictions.
Traceback (most recent call last):
  File "classify.py", line 695, in <module>
    random_state=args.random_state)
  File "classify.py", line 560, in train
    results['test'] = model.predict(X_test).tolist()
  File "/home/takeo/anaconda3/envs/dcase2020_tf1/lib/python3.7/site-packages/keras/engine/training.py", line 1380, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/home/takeo/anaconda3/envs/dcase2020_tf1/lib/python3.7/site-packages/keras/engine/training.py", line 757, in _standardize_user_data
    exception_prefix='input')
  File "/home/takeo/anaconda3/envs/dcase2020_tf1/lib/python3.7/site-packages/keras/engine/training_utils.py", line 131, in standardize_input_data
    'with shape ' + str(data_shape))
ValueError: Error when checking input: expected input to have 3 dimensions, but got array with shape (0, 1)
```

**Comment by shamss17** [comment]
Hii,
I am having the same error ,so if you solved it can you please tell me how !?

**Comment by JihunDev** [comment]
hello. @takeofuture @shamss17 

I am also getting the same error.
If you solved it, can you share how?

![SCR-20230227-mko](https://user-images.githubusercontent.com/5136900/221498346-961808f7-572a-487b-af0d-357152680780.png)
